# Generated by Django 4.2.11 on 2024-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_authors_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
